---
dependency:
  name: 'galaxy'
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: "sshd-${MOLECULE_DISTRO:-debian12}"
    image: "git.element-networks.nl/containers/${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: '/lib/systemd/systemd'
    pre_build_image: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
provisioner:
  name: 'ansible'
verifier:
  name: 'ansible'
